### ISSUE TITLE
Données à déplacer dans un fichier de constantes

### ISSUE THREAD

**Issue by Pierre-Loic** [DrunkCynicalUnicorn/OC_P5#2]
https://github.com/DrunkCynicalUnicorn/OC_P5/blob/64913ce675122c738306b7154c66380fb69f1d7d/apiReader_class.py#L6-L19

**Comment by DrunkCynicalUnicorn** [comment]
oui ce sont bien des constantes. Il y avait 2 raisons pour que je mette ça ici au départ : ce fichier est un brouillon en quelque sorte, pour bidouiller en testant facilement au fur et à mesure et sans accumuler trop de fichiers au départ (c'est aussi pour ça que le test auquel tu fais références en issue #1 était lui aussi rapidement écrit), mais également je trouvais que ça faisait sens de les placer ici en variables de classe, afin que tous les paramètres utilisés dans les requêtes API soient au même endroit. Mais si ce n'est pas vraiment la convention, je les déplacerai au moment de la structuration finale des fichiers.
