### ISSUE TITLE
Problem with association table

### ISSUE THREAD

**Issue by Pierre-Loic** [DrunkCynicalUnicorn/OC_P5#4]
https://github.com/DrunkCynicalUnicorn/OC_P5/blob/87150f921c68d0f8a37b52c8842f0a4514f3aae3/mysql_interface_class.py#L39

category_data[0] is a list because clean_data is list and data_cleaner return a list

**Comment by DrunkCynicalUnicorn** [comment]
problem solved with commit f427b87
